os: linux
language: java
jdk:
  - openjdk8

env:
  secure: HTRl35W6bwzXPYfRPZbMJZSey8D9fg1wdt0MMrftGO2uy8TdQrQLM8zZtGC+ej/i1AfngIe7C+1dBjcA1XiF/gO+pWmzvFa2ngY+5Xbyra2Xeg0VZBPVjP7MXbS5S/s1RMUtkAnXG7ScZoX1DfJ3EIXpEW2nUxK3mPHlWSKEvgVupOnQcQ88rFrz5gpZNx4ajNVQJQ+XlTv4DDT5kW7C6XofDW7GNAxisem/bBLtUJIfpaJBi7yPbnlOmKAZT607j8WGUpNWHzH4pRSZZXlpbMwwRFZCfIGGJ+92GY39c7MqDwxHNvY6DO3GTwKwpaXQfFvLbovnWweQy74zNgCWR2URMVH8ddiCTvxOON1jbrzUyO/b0Qv/Ryicdv7Wpc8SOh+Kyg0hHvVsNETZ3YQgpmMxjz+qtLoeoVxA4YeQIEYU8y6EhJtuzm6tmX8Inr3d+hzP3dr5rh8L7JJLwUMU1uGosIqt7yVLHhC9Pa+tQXL2PGy0mhgoP8Wui/lYwut+asbf79OsOkQwmO2z0jQr7k2m+jKr+BaCo4HGP4aALueUEn1ng+exzFk/MMiiEqVP+xqes562GxMA5vgghSmHulVn+kVHgbjjfGAhY7Uwm1UG14vvWFsBN+nu/115Kw3TOSbzmKx5jD71aaM3dRiQ0xptt+1kD7puUWvgjTUClCE=
